name: Build WPF (.NET Framework 4.7.2) without sln

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore (no packages, skip if none)
        run: echo "No packages to restore"

      - name: Build Release (csproj directly)
        run: msbuild YtDlpGui.Wpf\YtDlpGui.Wpf.csproj /t:Build /p:Configuration=Release /p:Platform="Any CPU" /m

      - name: Collect Artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          Copy-Item -Recurse -Force "YtDlpGui.Wpf\bin\Release\*" "artifacts\"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YtDlpGui.Wpf
          path: artifacts
